### ISSUE TITLE
Status/quality page or endpoint

### ISSUE THREAD

**Issue by 2ion** [tfabritius/pr-www#163]
ATM, portfolio-report.net does not seem to return any data for 2021-08-04 - 2021-08-05 on XETRA (did not try all endpoints). While I can pretty safely assume that the original data source is simply not returning up to date data, perhaps it's useful to expose the status of the "oracle" somehow so users of the service know about transient issues with the data quality and data availability.

For example, supply a status page which indicates for which exchanges and symbols data is not up to date (since when, for which intervals, for what reason), or make it clear which exchanges for specific security lag behind.

If a data source requires licensing or usage fees, this would also be a good way to make need of support transparent, by showing a page with paid data sources which are "down" due to usage limits getting reached.

**Comment by tfabritius** [comment]
Thanks for the hint. There was a hiccup in the data loading. It's fixed and 2021-08-04 should be available soon. 2021-08-05 will be available tomorrow.

I fully understand your proposal. Unfortunately, it is not that easy to automatically identify missing data and reasons.

There are many areas of improvement for sure. If you or anybody else would like to contribute, just let me know.
