### ISSUE TITLE
security type is ignored for query

### ISSUE THREAD

**Issue by OnkelDok** [tfabritius/pr-www#223]
**Describe the bug**
As described in buchen/portfolio#2483  the selected security type is not used for query results.

**To Reproduce**
1. Go to https://www.portfolio-report.net/search?q=sberbank&securityType=share
2. List of results contains bonds, shares and fonds even though a security type filter is set

**Expected behavior**
Only shares should be displayed as result.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/90478568/139740560-eaa9afd9-ffae-49a6-8f65-61cf65dd6d8d.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Browser

**Comment by tfabritius** [comment]
Thanks for reporting. Fixed in https://github.com/tfabritius/pr/commit/eefd9bb71ddbb4925cb2528774fe7ffb92c5cd0c.
