### ISSUE TITLE
Search returns unexpected results

### ISSUE THREAD

**Issue by ogig33** [tfabritius/pr-www#224]
**Describe the bug**
The search returns many results that are not relevant, e.g. a search with only one term "sberbank" returns 10 results, only one has the search term in the name, for the other 9 I have no clue why they appear. Enforcing an exact search via quotation marks seems also not working (only changes the rank of the correct result from 1 to 5).

**To Reproduce**
1. Open this link https://www.portfolio-report.net/search?q=sberbank

**Expected behavior**
The search should only return results matching the search term.

**Screenshots**

**Desktop (please complete the following information):**
 - Browser: Safari

**Comment by tfabritius** [comment]
The search intentionally allows fuzzy, non-exact matches. It's a tradeoff between returning potentially irrelevant matches and cutting of relevant matches.

I'd be open to improve the functionality, e.g. forcing exact matches via quotes, as PR.

**Comment by ogig33** [comment]
I think right now the distance between the search term and the results seems unexpectedly high, defeating the benefits over an exact search if only one term is used (probably majority of the searches).

I have been digging a bit through the code (not really skilled enough for a PR): you should be able to improve results by using Fuse.js `threshold` and `distance` options (https://fusejs.io/api/options.html). 
- `Threshold` is currently not set, this could be set to something less than 1.
- `Distance` ist not set either, this could be set to something less than 100 (current default).

The respective code is located here: https://github.com/tfabritius/pr-www/blob/33479641f2bc094970e00397ea366d0831d8ed50/api/inc/fts.ts
